[package]
name = "system_api"
version = "0.1.0"
edition = "2021"

[dependencies]
common_api.workspace = true

candid.workspace = true
ic-cdk.workspace = true

serde.workspace = true

rand.workspace = true
rand_chacha.workspace = true
fastrand = "2.3"

chrono.workspace = true
