[package]
name = "backend_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
backend_api = { path = "../api" }
backend_macros = { path = "../macros" }

candid.workspace = true
ic-cdk.workspace = true
ic-cdk-timers = "0.11"
ic-stable-structures = "0.6"

serde.workspace = true

rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3", default-features = false }

chrono = { version = "0.4", default-features = false, features = ["std"] }
uuid = "1.11"

[dev-dependencies]
candid_parser.workspace = true
mockall = "0.13"
rstest = "0.23"
