name: Codestyle

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Format
        run: pnpm format:check

  lint:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Lint
        run: pnpm lint
