name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust_tests:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create frontend dist directory
        run: |
          cd src/frontend
          mkdir -p dist

      - name: Cargo test
        run: cargo test
